// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// parsefile
void parsefile(std::string filename, int interval, int variance);
RcppExport SEXP _getais_parsefile(SEXP filenameSEXP, SEXP intervalSEXP, SEXP varianceSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< int >::type variance(varianceSEXP);
    parsefile(filename, interval, variance);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_getais_parsefile", (DL_FUNC) &_getais_parsefile, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_getais(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
